#!/bin/bash

session="tanner"

tmux start-server
tmux new-session -d -s $session

if [[ -n $1 ]]
then
  tmux send-keys "vim ${1}" C-m
else
  tmux send-keys "vim" C-m
fi
 
tmux splitw -v -p 5
tmux selectp -t 0
tmux attach-session -t $session
